site_name: CliMe
site_url: https://example.com/
nav:
    - CliMe: 'index.md'
    - About: 'about.md'
    - Tutorials:
        - Strings:
          - Intro: 'tutorials/strings/index.md'
          - Positional: 'tutorials/strings/positional.md'
          - Default Values: 'tutorials/strings/defaults.md'
          - Optional Default Values: 'tutorials/strings/optional_defaults.md'
        - Using Attrib:
          - Intro: 'tutorials/superchargewithattrib/index.md'
          - Converters: 'tutorials/superchargewithattrib/converters.md'

markdown_extensions:
    - toc:
        permalink: true
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs
    - admonition
    - codehilite
    - extra
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format
    - pymdownx.tabbed

theme: readthedocs