from pathlib import Path

CLASSES_WITH_SPECLIAL_CLIME_HANDLING_DIRECTLY_BY_ARGPASER = {
    str,
    bool,
}

CLASSES_HANDLED_DIRECTLY_BY_ARGPASER = {
    int,
    float,
    ord,
    str,
}

OTHER_CLASSES_THAT_WILL_WORK_WELL = {
    Path,
}
KNOWN_CLASS_TYPES_THAT_WILL_WORK_WELL = (
    CLASSES_WITH_SPECLIAL_CLIME_HANDLING_DIRECTLY_BY_ARGPASER.intersection(
        CLASSES_HANDLED_DIRECTLY_BY_ARGPASER
    ).intersection(OTHER_CLASSES_THAT_WILL_WORK_WELL)
)
